-- Create users.
DROP USER lddbUser CASCADE;
CREATE USER lddbUser IDENTIFIED BY bjarne;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER, CREATE VIEW, CREATE MATERIALIZED VIEW, UNLIMITED TABLESPACE, CREATE SEQUENCE TO lddbUser;

DROP DIRECTORY exp_dir;
CREATE DIRECTORY exp_dir AS 'C:\Users\drd26\Documents\project';
GRANT READ, WRITE ON DIRECTORY exp_dir to lddbUser;


-- Load the database.
@load.sql