-- Create users.
CREATE USER lddbUser IDENTIFIED BY yourPassword;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, UNLIMITED TABLESPACE, CREATE SEQUENCE TO lddbUser;

-- Load the database.
@load.sql