-- Create users.
DROP USER lddbUser CASCADE;
CREATE USER lddbUser IDENTIFIED BY bjarne;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE VIEW, CREATE MATERIALIZED VIEW, UNLIMITED TABLESPACE, CREATE SEQUENCE TO lddbUser;

-- Load the database.
@load.sql